export const Assets = {
  CheckOut: {
    CreditCard: "/assets/images/checkout/credit-card.png",
    Gpay: "/assets/images/checkout/gpay.png",
    MasterCard: "/assets/images/checkout/master-card.png",
    StripeCard: "/assets/images/checkout/stripe-card.png",
    PayFastCard: "/assets/images/checkout/payfast-card.png",
    ProImageCheckout: "/assets/images/checkout/pro-image-checkout.png",
  },
  Dashboard: {
    Billing: "/assets/images/dashboard/billing-icon.svg",
    Dashboard: "/assets/images/dashboard/dashboard.svg",
    Download: "/assets/images/dashboard/download-icon.svg",
    Four: "/assets/images/dashboard/four.jpg",
    Logout: "/assets/images/dashboard/logout-icon.svg",
    Notification: "/assets/images/dashboard/notification-icon.svg",
    One: "/assets/images/dashboard/one.jpg",
    OneW: "/assets/images/dashboard/onew.jpg",
    RightArrow: "/assets/images/dashboard/right-arrow.svg",
    Settings: "/assets/images/dashboard/settings-icon.svg",
    Three: "/assets/images/dashboard/three.jpg",
    Two: "/assets/images/dashboard/two.jpg",
    WishList: "/assets/images/dashboard/wishlist-icon.svg",
  },
  Marketplace: {
    Flower: "/assets/images/marketplace/3D-flower.png",
    Image202: "/assets/images/marketplace/202.png",
    Image294: "/assets/images/marketplace/294.png",
    Aflam: "/assets/images/marketplace/Aflam.png",
    AngelList: "/assets/images/marketplace/angellist.svg",
    Animated1: "/assets/images/marketplace/anim1.png",
    Animated2: "/assets/images/marketplace/anim2.png",
    Animated3: "/assets/images/marketplace/anim3.png",
    Astronaut: "/assets/images/marketplace/astronaut.png",
    Cart: "/assets/images/marketplace/cart-icon.svg",
    Cart2: "/assets/images/marketplace/Cart.svg",
    CmhLogo: "/assets/images/marketplace/creative-media-hub-logo.svg",
    Dribble: "/assets/images/marketplace/dribble.svg",
    Facebook: "/assets/images/marketplace/facebook.svg",
    Eye: "/assets/images/marketplace/eye.svg",
    Elite: "/assets/images/marketplace/Elite.png",
    GetStarted: "/assets/images/marketplace/getStarted.png",
    Github: "/assets/images/marketplace/github.svg",
    Slider1: "/assets/images/marketplace/slider1.png",
    LeftArrow: "/assets/images/marketplace/left-arrow.png",
    Linkedin: "/assets/images/marketplace/linkedin.svg",
    LoginBg: "/assets/images/marketplace/login-bg.png",
    LoginScreenShape: "/assets/images/marketplace/login-screen-shape.svg",
    MainBanner: "/assets/images/marketplace/marketplace-main-banner.png",
    Paramid: "/assets/images/marketplace/paramid.png",
    Search: "/assets/images/marketplace/search-icon.svg",
    HomeSlide1: "/assets/images/marketplace/slide1.png",
    HomeSlide2: "/assets/images/marketplace/slide2.png",
    Spector: "/assets/images/marketplace/spector.png",
    Twitter: "/assets/images/marketplace/twitter.svg",
  },
};
